### PR TITLE
MVM remote monitoring

### PR DESCRIPTION
**Pull request by guescio**
Implemented support for remote monitoring in mvm-control. Tested with MVM mock and it works fine.

### CODE REVIEW

**Comment by bryerton** [comment]
Please add an argument to select an JSON configuration file for the MQTT broker, topic, log format etc. so that anyone can do the remote logging. This means monitorconfig.py should disappear, and mvm_control.py will use the settings from the JSON file. As this tool is meant to be used from the command line from anywhere, and installed via pip, having a second python file to do a fixed configuration is not acceptable. Doing it this way is also not very flexible, as you have to edit the remoteconfig.py to adjust the settings.

Quiet suggests no print output (which is what normally occurs), please we switch to -n / --no-log-file instead.

**Comment by guescio** [comment]
Hi Bryerton, I have implemented the use a JSON config file for the monitoring (`--monitor-config`) and replaced the `--quiet` option with `--no-log`. What do you think?

**Comment by bryerton** [comment]
So I had time to do a more detailed review, I've pushed some changes to the mvm-monitor branch, and will accept it. But I'd like to note the following:

1) Don't adjust a non-default rate just because remote monitoring is on, the user made the choice (unless you have a technical reason for this?)
2) Python2 is being supported here, code must be python2 & 3 compatible. If you use 'tox' the testing for this is simple. You can install it via `pip install tox` and run it by typing `tox` in the base dir of the project. 
3) All dependencies needed must be added to pyproject.toml, using tox helps with this dependency check.
4) This option of remote monitoring should be available for clog and log
5) It would be nice if you ran flake8 against the code prior to commit
6) Could you add more details to README.md on the format of the monitor configuration
7) I appreciate you contributing to this project! I know there is much to do, and plenty of cleanup of the existing code that should be done. Help with linting and testing would be appreciated.

**Comment by guescio** [comment]
Thank you for merging!
I have implemented your suggestions in the other merge request I have just submitted.
1. I want to avoid overloading the server. I might relax this requirement in the future.
4. I did not implement monitoring in clog for the same reason as point 1. I cannot test clog but from what I understood the rate of the data output is higher than 10 Hz.
7. And I really appreciate your feedback!

**Pull request merged**
