### PR TITLE
Name of the last field returned by "get all"

### PR DESCRIPTION
**Pull request by guescio**
Updating the name of the last field returned by `get all` from `f_peak` to `v_minute`. See:
 - https://github.com/NuclearInstruments/MVMFirmware/blob/master/ArduinoCorePP_PWM_hw_v3/ArduinoCorePP_PWM_hw_v3.ino#L1501
 - https://github.com/NuclearInstruments/MVMFirmware/blob/master/ArduinoCorePP_PWM_hw_v4/ArduinoCorePP_PWM_hw_v4.ino#L1579
 - https://github.com/NuclearInstruments/MVMFirmwareCpp/blob/master/MVMFirmwareCore/ConfigManager.cpp#L400

### CODE REVIEW

**Comment by bryerton** [comment]
I'm going to run this by Michael. I know the FW code got updated and
changed what this var represents, but adjusting the field name here means
log parsing tools will need to also update.

Not sure if it's worth it to change the name of it means breaking parsing
for others.

**Comment by bryerton** [comment]
I'm going to leave this field alone, there is too much log data already taken, and I feel adjusting it might break someone's parser. Michael has informed me other groups have simply renamed the field(s) when importing to what they desire.

**Comment by guescio** [comment]
I see the point. However there will be more data coming and the data we got so far is from prototypes. I think we should take the chance to update the naming once we move to the next series of prototypes and the new firmware.  The use of `backup_min_ratio` and `backup_min_time` is another example. I'll bring this up at the next analysis meeting.

**Comment by bryerton** [comment]
Sounds good, I'm certainly not opposed to changing the script to match the
firmware, When the backup_min_X switch happened though, the hw_version
didn't change initially and it became annoying to differentiate (you had to
try one of the command variants and let it timeout or succeed to test) so I
left it until development settled more.

For the next update my plan is to switch to using a JSON config file to
setup the set/get command list and the field names for log and clog, with
internal pre-builts auto-selected on hw_version if no file specified. This
will save effort attempting to keep up with changing firmware. I should
have written that way in the first place, but c'est la vie.

**Pull request closed without merging**
